"""Conversation export helpers with themed highlighting."""

from __future__ import annotations

import json
from dataclasses import asdict
from html import escape
from pathlib import Path
from typing import Iterable, Mapping

from ..theme import TERMINAL_THEME

Message = Mapping[str, object]


def export_to_markdown(messages: Iterable[Message], export_path: str) -> Path:
    """Export the provided messages to a Markdown file with inline styling."""

    markdown = messages_to_markdown(messages)
    path = Path(export_path)
    path.write_text(markdown, encoding="utf-8")
    print(f"Exported current conversation to {path}")
    return path


def export_to_notebook(messages: Iterable[Message], export_path: str) -> Path:
    """Export the provided messages to a Jupyter notebook."""

    nbformat, new_code_cell, new_markdown_cell, new_notebook = _load_nbformat()

    notebook = new_notebook()
    cells = []

    for chunk in messages:
        role = str(chunk.get("role", "assistant")).capitalize()
        chunk_type = chunk.get("type")
        content = chunk.get("content") or ""

        if chunk_type == "message":
            text = f"**{role}**\n\n{content}"
            cells.append(new_markdown_cell(text))
        elif chunk_type == "code":
            language = chunk.get("format") or "python"
            cell = new_code_cell(content)
            cell.metadata.setdefault("open_interpreter", {})["theme"] = asdict(TERMINAL_THEME)
            cell.metadata["language"] = language
            cells.append(cell)
        elif chunk_type == "console":
            styled = _html_console_block(content)
            cells.append(new_markdown_cell(styled))
        else:
            cells.append(new_markdown_cell(content))

    notebook["cells"] = cells

    path = Path(export_path)
    with path.open("w", encoding="utf-8") as handle:
        nbformat.write(notebook, handle)

    print(f"Jupyter notebook file exported to {path}")
    return path


def export_to_json(messages: Iterable[Message], export_path: str) -> Path:
    """Export the provided messages to JSON."""

    path = Path(export_path)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(list(messages), handle, indent=2)
    print(f"Conversation JSON exported to {path}")
    return path


def messages_to_markdown(messages: Iterable[Message]) -> str:
    """Convert conversation messages to Markdown with themed code blocks."""

    sections: list[str] = [
        "<!-- Generated by Open Interpreter with themed highlights -->",
    ]

    for chunk in messages:
        role = str(chunk.get("role", "assistant")).capitalize()
        chunk_type = chunk.get("type")
        content = chunk.get("content") or ""

        if chunk_type == "message":
            sections.append(_html_message_block(role, content))
        elif chunk_type == "code":
            sections.append(_html_code_block(content, chunk.get("format")))
        elif chunk_type == "console":
            sections.append(_html_console_block(content))
        else:
            sections.append(f"### {role}\n\n{content}")

    return "\n\n".join(sections)


# ---------------------------------------------------------------------------
# HTML helper blocks
# ---------------------------------------------------------------------------

def _html_message_block(role: str, content: str) -> str:
    body = escape(content).replace("\n", "<br>")
    return (
        f"<div style='background:{TERMINAL_THEME.message_background};color:{TERMINAL_THEME.message_text};"
        f"border-left:3px solid {TERMINAL_THEME.message_border};padding:12px 16px;margin:12px 0;'>"
        f"<strong>{escape(role)}</strong><br>{body}</div>"
    )


def _html_code_block(content: str, language: object | None) -> str:
    lang = escape(str(language or "text"))
    code = escape(content)
    return (
        f"<pre style='background:{TERMINAL_THEME.code_background};color:{TERMINAL_THEME.code_cursor};"
        "padding:12px;border-radius:10px;overflow:auto;'>"
        f"<code class='language-{lang}'>{code}</code></pre>"
    )


def _html_console_block(content: str) -> str:
    text = escape(content)
    return (
        f"<pre style='background:{TERMINAL_THEME.console_background};color:{TERMINAL_THEME.console_text};"
        "padding:12px;border-radius:10px;overflow:auto;'>"
        f"<code>{text}</code></pre>"
    )


def _load_nbformat():
    try:
        import nbformat
        from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook
    except ImportError as exc:  # pragma: no cover - handled at runtime
        raise RuntimeError(
            "nbformat is required for notebook exports. Install it with `pip install nbformat`."
        ) from exc
    return nbformat, new_code_cell, new_markdown_cell, new_notebook


__all__ = [
    "export_to_markdown",
    "export_to_notebook",
    "export_to_json",
    "messages_to_markdown",
]
